# Generated by Django 4.1.11 on 2023-09-19 18:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_widgetdocumentation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widgetdocumentation",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", wagtail.blocks.RichTextBlock())],
                use_json_field=True,
            ),
        ),
    ]
